### ISSUE TITLE
C++ ADDONS Error

### ISSUE THREAD

**Issue by ramprasad2018** [freezer333/nodecpp-demo#15]
Node.js Version: v10.13.0
OS: Windows 7
Scope (install, code, runtime, meta, other?): code
Module (and version) (if relevant): ADDONS for C++
Issue: - The npm-gyp configure command is getting failed.
Question: - Why the npm-gyp is calling the Python ? Is it mandatory? Even if needed, how to resolve the Python Error ? How to get rid of Python, as my aim is to call only C++.

Attached : - The screenshot of the error and the project folder.
Error:
C:\Ram\Projects\GraphQL\t\addon>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Software\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack File "", line 1
gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack at Socket.emit (events.js:182:13)
gyp ERR! stack at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\software\nodejs\node.exe" "C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "configure"
gyp ERR! cwd C:\Ram\Projects\GraphQL\t\addon
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
capture

Package.json:

{
"name": "my_addon",
"version": "0.0.0",
"description": "My reusable C++ addon",
"gypfile": true,
"main": "./build/Release/my_addon",
"license": "1.0",
"dependencies": {
"nan": "^2.3.3",
"node-gyp": "^3.8.0"
}
}
![capture](https://user-images.githubusercontent.com/43319298/48316511-9308c400-e61f-11e8-882f-6bf08f7a1c7e.JPG)

capture
addon.zip
[addon.zip](https://github.com/freezer333/nodecpp-demo/files/2569659/addon.zip)

**Comment by ramprasad2018** [comment]
Hi Freezer,
The issue is resolve after following the instructions at 
https://www.npmjs.com/package/node-gyp#on-windows

Thanks and regards,
Ram
